// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVzrA7Uv177FVmv_EQv2i6tWiv_JcFOww',
    appId: '1:443690479496:web:ca3ced82a2a25a9da1d43d',
    messagingSenderId: '443690479496',
    projectId: 'canvascast-7c86e',
    authDomain: 'canvascast-7c86e.firebaseapp.com',
    storageBucket: 'canvascast-7c86e.firebasestorage.app',
    measurementId: 'G-GCD182R6ES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWKk2BFUVt5jzhRzDsuvdnMSYBPy0CCXk',
    appId: '1:443690479496:android:a1db73fe5932931da1d43d',
    messagingSenderId: '443690479496',
    projectId: 'canvascast-7c86e',
    storageBucket: 'canvascast-7c86e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnXSWKxKi5UuThJRZmd0TKpQcl8gOzfjc',
    appId: '1:443690479496:ios:92cc55b1904bb624a1d43d',
    messagingSenderId: '443690479496',
    projectId: 'canvascast-7c86e',
    storageBucket: 'canvascast-7c86e.firebasestorage.app',
    iosBundleId: 'com.example.assignmentquestion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnXSWKxKi5UuThJRZmd0TKpQcl8gOzfjc',
    appId: '1:443690479496:ios:92cc55b1904bb624a1d43d',
    messagingSenderId: '443690479496',
    projectId: 'canvascast-7c86e',
    storageBucket: 'canvascast-7c86e.firebasestorage.app',
    iosBundleId: 'com.example.assignmentquestion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVzrA7Uv177FVmv_EQv2i6tWiv_JcFOww',
    appId: '1:443690479496:web:a51adf879d19f05ea1d43d',
    messagingSenderId: '443690479496',
    projectId: 'canvascast-7c86e',
    authDomain: 'canvascast-7c86e.firebaseapp.com',
    storageBucket: 'canvascast-7c86e.firebasestorage.app',
    measurementId: 'G-GF7LLM42E7',
  );
}
